mountpoint expects noting instead of self.device and path is optional fixes: AttributeError: 'SamsungSdMuxController' object has no attribute 'device'
Signed-off-by: Mayuri Mohite <MayuriMohan_Mohite@mentor.com>