fix(power): fix libgpiod imports for V1 based systems
libgpiod-v1 does not have a "real" python package but rather a single C
binding library.
Starting with libgpiod-v2 imports like gpiod.* starts to work.

Bookworm installs python3-libgpiod v1.6 whereas trixie installs the v2.2.

The produced error on bookworm looks as follows:

  error: power could not be found/loaded!

Signed-off-by: Benedikt Niedermayr <benedikt.niedermayr@siemens.com>
Fixes: 1cce630116bb ("feat(power): support for python3-libgpiod v2")